"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import type { ScoreEntry, TeamDTO } from "@/types";
import { useSession } from "@/app/components/SessionProvider";
import { formatDate } from "@/lib/utils";

// Printable scores report. Opened from the Scores page with the same filters:
//   /dashboard/scores/report?team=&dateFrom=&dateTo=
// Use the browser's print dialog ("Save as PDF") to export it.
function ReportContent() {
  const session = useSession();
  const params = useSearchParams();
  const team = params.get("team") ?? "";
  const dateFrom = params.get("dateFrom") ?? "";
  const dateTo = params.get("dateTo") ?? "";

  const [scores, setScores] = useState<ScoreEntry[]>([]);
  const [teams, setTeams] = useState<TeamDTO[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [generatedAt] = useState(() => new Date());

  useEffect(() => {
    const qs = new URLSearchParams();
    if (team) qs.set("team", team);
    if (dateFrom) qs.set("dateFrom", dateFrom);
    if (dateTo) qs.set("dateTo", dateTo);

    let cancelled = false;
    (async () => {
      try {
        const [scoresRes, teamsRes] = await Promise.all([
          fetch(`/api/scores${qs.toString() ? `?${qs}` : ""}`),
          session.role !== "employee" ? fetch("/api/teams") : Promise.resolve(null),
        ]);
        const scoresData = await scoresRes.json();
        if (!scoresRes.ok) throw new Error(scoresData.error ?? "Could not load scores.");
        const teamsData = teamsRes ? await teamsRes.json() : null;
        if (cancelled) return;
        setScores(scoresData.scores ?? []);
        setTeams(teamsData?.teams ?? []);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : "Could not load scores.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [team, dateFrom, dateTo, session.role]);

  const totals = useMemo(() => {
    const assigned = scores.reduce((sum, s) => sum + s.totalAssigned, 0);
    const completed = scores.reduce((sum, s) => sum + s.totalCompleted, 0);
    return {
      assigned,
      completed,
      rate: assigned > 0 ? Math.round((completed / assigned) * 100) : 0,
    };
  }, [scores]);

  const scopeLabel =
    session.role === "employee"
      ? session.name
      : team
        ? (teams.find((t) => t._id === team)?.name ?? "Selected team")
        : "All teams";

  const periodLabel =
    dateFrom || dateTo
      ? `${dateFrom ? formatDate(dateFrom) : "Beginning"} – ${dateTo ? formatDate(dateTo) : "Today"}`
      : "All time";

  return (
    <div className="report">
      {/* Toolbar: hidden when printing */}
      <div className="flex items-center justify-between mb-6 print:hidden">
        <Link href="/dashboard/scores" className="text-sm text-ink/60 hover:text-ink">
          ← Back to scores
        </Link>
        <button
          className="btn-primary"
          onClick={() => window.print()}
          disabled={loading || !!error}
        >
          Print / Save as PDF
        </button>
      </div>

      <div className="card p-8 print:border-0 print:p-0 print:rounded-none">
        <header className="mb-6 pb-4 border-b border-ink/15">
          <p className="text-xs uppercase tracking-widest text-ink/50 mb-1">Meridian</p>
          <h1 className="font-display text-3xl mb-3">Scores report</h1>
          <dl className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm">
            <div className="flex gap-2">
              <dt className="text-ink/50">Scope:</dt>
              <dd className="font-medium">{scopeLabel}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-ink/50">Period:</dt>
              <dd className="font-medium">{periodLabel}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-ink/50">Generated:</dt>
              <dd className="font-medium">
                {generatedAt.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}
              </dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-ink/50">Generated by:</dt>
              <dd className="font-medium">{session.name}</dd>
            </div>
          </dl>
        </header>

        {loading ? (
          <p className="text-ink/50">Loading…</p>
        ) : error ? (
          <p className="text-clay">{error}</p>
        ) : (
          <>
            <section className="grid grid-cols-4 gap-4 mb-6">
              <Stat label="Employees" value={scores.length} />
              <Stat label="Tasks assigned" value={totals.assigned} />
              <Stat label="Tasks approved" value={totals.completed} />
              <Stat label="Overall score" value={`${totals.rate}%`} />
            </section>

            <table className="w-full text-sm">
              <thead className="text-left text-ink/60 border-b border-ink/20">
                <tr>
                  <th className="py-2 pr-3 font-medium w-10">#</th>
                  <th className="py-2 pr-3 font-medium">Employee</th>
                  <th className="py-2 pr-3 font-medium">Department</th>
                  <th className="py-2 pr-3 font-medium text-right">Approved</th>
                  <th className="py-2 pr-3 font-medium text-right">Assigned</th>
                  <th className="py-2 font-medium text-right">Score</th>
                </tr>
              </thead>
              <tbody>
                {scores.length === 0 ? (
                  <tr>
                    <td className="py-6 text-ink/50" colSpan={6}>
                      No task data for this selection.
                    </td>
                  </tr>
                ) : (
                  scores.map((entry, i) => (
                    <tr key={entry.employee._id} className="border-b border-ink/10 break-inside-avoid">
                      <td className="py-2 pr-3 text-ink/50">{i + 1}</td>
                      <td className="py-2 pr-3 font-medium">{entry.employee.name}</td>
                      <td className="py-2 pr-3 text-ink/70">{entry.employee.department}</td>
                      <td className="py-2 pr-3 text-right">{entry.totalCompleted}</td>
                      <td className="py-2 pr-3 text-right">{entry.totalAssigned}</td>
                      <td className="py-2 text-right font-medium">{entry.score}%</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>

            <p className="mt-6 text-xs text-ink/50">
              Score = tasks approved ÷ tasks assigned (1 point per task), counting tasks scheduled
              within the period above.
            </p>
          </>
        )}
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="rounded-lg border border-ink/10 px-4 py-3">
      <p className="text-xs text-ink/50">{label}</p>
      <p className="font-display text-2xl">{value}</p>
    </div>
  );
}

export default function ScoresReportPage() {
  return (
    <Suspense fallback={<p className="text-ink/50">Loading report…</p>}>
      <ReportContent />
    </Suspense>
  );
}
